import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const createDynamicStyles = (isDarkMode: boolean) => ({
  container: {
    backgroundColor: isDarkMode ? '#121212' : '#F8F8F8',
  },
  darkText: {
    color: '#FFFFFF',
  },
  darkSubtext: {
    color: 'rgba(255, 255, 255, 0.7)',
  },
  darkInput: {
    backgroundColor: '#2A2A2A',
    borderColor: '#3A3A3A',
    color: '#FFFFFF',
  },
  darkExerciseContainer: {
    backgroundColor: '#1E1E1E',
    borderColor: '#3A3A3A',
    borderLeftColor: '#6200EE',
  },
  darkRemoveIconButton: {
    backgroundColor: 'rgba(255, 59, 48, 0.2)',
  },
  darkAddButton: {
    backgroundColor: '#2A2A2A',
    borderColor: '#3A3A3A',
  },
  darkAddButtonText: {
    color: '#FFFFFF',
  },
  darkSubmitButton: {
    backgroundColor: '#6200EE',
  },
  darkDivider: {
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
  },
  darkBackButton: {
    backgroundColor: isDarkMode ? 'rgba(255, 255, 255, 0.05)' : 'transparent',
    borderColor: isDarkMode ? 'rgba(255, 255, 255, 0.1)' : 'rgba(0, 0, 0, 0.1)',
  },
});

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8F8F8',
  },
  contentContainer: {
    paddingBottom: 40,
  },
  topBar: {
    paddingHorizontal: 10,
    paddingTop: 20,
    paddingBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 5,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    borderColor: 'rgba(0, 0, 0, 0.1)',
  },
  headerContainer: {
    marginBottom: 28,
    paddingHorizontal: 10,
    paddingTop: 10,
  },
  headerText: {
    fontSize: 28,
    fontWeight: '900',
    color: '#1A1A1A',
    letterSpacing: -0.5,
    textTransform: 'uppercase',
  },
  headerSubtext: {
    fontSize: 16,
    color: 'rgba(0, 0, 0, 0.6)',
    marginTop: 8,
    letterSpacing: 0.1,
  },
  formWrapper: {
    paddingHorizontal: 10,
  },
  formGroup: {
    marginBottom: 24,
  },
  label: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1A1A1A',
    marginBottom: 8,
    letterSpacing: -0.3,
    textTransform: 'uppercase',
  },
  input: {
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 5,
    padding: 16,
    fontSize: 16,
    backgroundColor: '#FFFFFF',
    color: '#1A1A1A',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
  },
  errorInput: {
    borderColor: '#FF3B30',
    borderLeftWidth: 4,
  },
  errorText: {
    color: '#FF3B30',
    fontSize: 12,
    marginTop: 4,
    fontWeight: '600',
    letterSpacing: -0.2,
  },
  exercisesHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
    marginTop: 8,
  },
  exercisesTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#1A1A1A',
    letterSpacing: -0.3,
  },
  exercisesCount: {
    fontSize: 14,
    color: 'rgba(0, 0, 0, 0.6)',
  },
  exerciseContainer: {
    marginBottom: 24,
    padding: 20,
    backgroundColor: '#FFFFFF',
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.15,
    shadowRadius: 5,
    elevation: 6,
    borderLeftWidth: 4,
    borderLeftColor: '#000000',
  },
  exerciseHeaderContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0, 0, 0, 0.08)',
    paddingBottom: 14,
  },
  exerciseHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  exerciseHeader: {
    fontSize: 17,
    fontWeight: '800',
    color: '#1A1A1A',
    marginLeft: 10,
    letterSpacing: -0.3,
    textTransform: 'uppercase',
  },
  removeIconButton: {
    padding: 10,
    backgroundColor: 'rgba(255, 59, 48, 0.12)',
    borderRadius: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 3,
    elevation: 3,
  },
  buttonContainer: {
    marginTop: 30,
    marginBottom: 40,
    gap: 20,
  },
  divider: {
    height: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.05)',
    marginVertical: 16,
  },
  addButton: {
    backgroundColor: '#FFFFFF',
    padding: 16,
    borderRadius: 5,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#000000',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  addButtonText: {
    color: '#000000',
    fontSize: 16,
    fontWeight: '700',
    marginLeft: 10,
    letterSpacing: -0.3,
  },
  submitButton: {
    backgroundColor: '#000000',
    padding: 18,
    borderRadius: 5,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 5,
    elevation: 6,
  },
  submitButtonText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '800',
    marginLeft: 10,
    letterSpacing: -0.3,
    textTransform: 'uppercase',
  },
});
