import { StyleSheet } from 'react-native';

export const createDynamicStyles = (isDarkMode: boolean) => ({
  container: {
    backgroundColor: isDarkMode ? '#121212' : '#FFFFFF',
  },
  darkText: {
    color: '#FFFFFF',
  },
  darkSubtext: {
    color: 'rgba(255, 255, 255, 0.7)',
  },
  darkInput: {
    backgroundColor: '#2A2A2A',
    borderColor: '#3A3A3A',
    color: '#FFFFFF',
  },
  darkExerciseContainer: {
    backgroundColor: '#1E1E1E',
    borderColor: '#3A3A3A',
  },
  darkRemoveIconButton: {
    backgroundColor: 'rgba(255, 59, 48, 0.2)',
  },
  darkAddButton: {
    backgroundColor: '#2A2A2A',
    borderColor: '#3A3A3A',
  },
  darkAddButtonText: {
    color: '#FFFFFF',
  },
  darkSubmitButton: {
    backgroundColor: '#1A1A1A',
  },
  darkDivider: {
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
  },
  accent: isDarkMode ? '#6200EE' : '#000000',
  buttonText: isDarkMode ? '#FFFFFF' : '#FFFFFF',
  buttonBackground: isDarkMode ? '#1A1A1A' : '#000000',
  danger: isDarkMode ? '#CF6679' : '#B00020',
  success: isDarkMode ? '#03DAC6' : '#018786',
});

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 20,
    backgroundColor: '#FFFFFF',
  },
  headerContainer: {
    marginBottom: 24,
  },
  headerText: {
    fontSize: 22,
    fontWeight: '900',
    color: '#1A1A1A',
    letterSpacing: -0.5,
    textTransform: 'uppercase',
  },
  headerSubtext: {
    fontSize: 14,
    color: 'rgba(0, 0, 0, 0.6)',
    marginTop: 4,
    letterSpacing: 0.1,
  },
  formGroup: {
    marginBottom: 20,
  },
  label: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1A1A1A',
    marginBottom: 8,
    letterSpacing: -0.3,
    textTransform: 'uppercase',
  },
  input: {
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 8,
    padding: 14,
    fontSize: 16,
    backgroundColor: '#FFFFFF',
    color: '#1A1A1A',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
  },
  errorInput: {
    borderColor: '#FF3B30',
    borderLeftWidth: 4,
  },
  errorText: {
    color: '#FF3B30',
    fontSize: 12,
    marginTop: 4,
    fontWeight: '600',
    letterSpacing: -0.2,
  },
  exerciseContainer: {
    marginTop: 16,
    padding: 16,
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
    borderLeftWidth: 4,
    borderLeftColor: '#000000',
  },
  exerciseHeaderContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  exerciseHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  exerciseHeader: {
    fontSize: 16,
    fontWeight: '800',
    color: '#1A1A1A',
    marginLeft: 8,
    letterSpacing: -0.3,
    textTransform: 'uppercase',
  },
  removeIconButton: {
    padding: 8,
    backgroundColor: 'rgba(255, 59, 48, 0.1)',
    borderRadius: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  buttonContainer: {
    marginTop: 24,
    marginBottom: 32,
    gap: 16,
  },
  divider: {
    height: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.05)',
    marginVertical: 12,
  },
  addButton: {
    backgroundColor: '#FFFFFF',
    padding: 16,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#000000',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 3,
    elevation: 3,
  },
  addButtonText: {
    color: '#000000',
    fontSize: 16,
    fontWeight: '800',
    marginLeft: 8,
    letterSpacing: -0.3,
    textTransform: 'uppercase',
  },
  submitButton: {
    backgroundColor: '#000000',
    padding: 16,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  submitButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '800',
    marginLeft: 8,
    letterSpacing: -0.3,
    textTransform: 'uppercase',
  },
});
