import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#FAFAFA', // Default background color
  },
  scrollView: {
    flex: 1,
    paddingTop: 0,
    overflow: 'hidden',
  },
  headerContainer: {
    marginBottom: 24,
    paddingHorizontal: 20,
  },
  headerTitle: {
    fontSize: 28,
    fontWeight: '900',
    color: '#000000',
    marginBottom: 8,
    letterSpacing: -0.5,
    textTransform: 'uppercase',
  },
  headerSubtitle: {
    fontSize: 15,
    color: '#6B7280',
    lineHeight: 20,
    letterSpacing: 0.1,
    opacity: 0.9,
  },
  sectionContainer: {
    marginBottom: 24,
    paddingHorizontal: 20,
  },
  sectionTitle: {
    fontSize: 17,
    fontWeight: '500',
    color: '#000000',
    marginBottom: 16,
    letterSpacing: -0.2,
  },
  carouselContainer: {
    marginHorizontal: -20,
    paddingHorizontal: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 4,
  },
  horizontalScroll: {
    paddingVertical: 12,
    paddingLeft: 5,
  },
  workoutButton: {
    marginRight: 20,
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 4,
    minWidth: 140,
    height: 75,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    position: 'relative',
    overflow: 'hidden',
  },
  selectedWorkoutButton: {
    backgroundColor: '#000000',
    borderColor: '#000000',

    shadowOpacity: 0.25,
    shadowOffset: { width: 0, height: 4 },
    transform: [{ scale: 1.05 }],
  },
  unselectedWorkoutButton: {
    backgroundColor: '#FFFFFF',
    borderColor: '#DDDDDD',
  },
  workoutButtonText: {
    fontWeight: '800',
    fontSize: 16,
    textAlign: 'center',
    letterSpacing: -0.3,
    textTransform: 'uppercase',
  },
  selectedWorkoutButtonText: {
    color: '#FFFFFF',
  },
  unselectedWorkoutButtonText: {
    color: '#000000',
  },
  carouselIndicator: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 20,
    marginBottom: 8,
  },
  indicatorDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    marginHorizontal: 4,
    backgroundColor: '#CCCCCC',
    opacity: 1,
  },
  activeIndicatorDot: {
    backgroundColor: '#000000',
    width: 28,
    height: 8,
    borderRadius: 2,
    opacity: 1,
  },
  selectionHint: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 10,
    height: 10,
    borderRadius: 2,
    backgroundColor: '#FFFFFF',
  },
  viewModeSection: {
    alignItems: 'center',
    marginBottom: 24,
    marginTop: 10,
  },
  viewToggleContainer: {
    flexDirection: 'row',
    borderRadius: 8,
    height: 48,
    width: '90%',
    maxWidth: 360,
    backgroundColor: '#E0E0E0',
    padding: 4,

    elevation: 2,
  },
  viewToggleButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 6,
    height: '100%',
    marginHorizontal: 2,
  },
  activeViewToggleButton: {
    backgroundColor: '#000000',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
    borderRadius: 0,
    position: 'relative',
    zIndex: 1,
    marginHorizontal: 0,
    paddingVertical: 10,
    paddingHorizontal: 8,
    // Clean underline effect
    borderBottomWidth: 3,
    borderBottomColor: 'rgba(255,255,255,0.9)',
    // No other borders
    borderWidth: 0,
    // No transforms
    transform: [],
  },
  viewToggleIcon: {
    marginRight: 8,
  },
  viewToggleText: {
    fontSize: 16,
    fontWeight: '600',
    letterSpacing: -0.2,
  },
  progressContainer: {
    marginBottom: 32,
    marginHorizontal: 20,
  },
  progressCard: {
    backgroundColor: '#FFFFFF',
    paddingVertical: 24,
    paddingHorizontal: 20,
    borderRadius: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#F5F5F5',
  },
  progressCardTitle: {
    fontSize: 22,
    fontWeight: '800',
    marginBottom: 6,
    color: '#000000',
    letterSpacing: -0.5,
    textTransform: 'uppercase',
  },
  progressCardSubtitle: {
    fontSize: 15,
    color: '#6B7280',
    marginBottom: 24,
    letterSpacing: 0.1,
    fontWeight: '400',
    opacity: 0.9,
  },
  exerciseContainer: {
    marginBottom: 28,
  },
  exerciseDivider: {
    borderBottomWidth: 1,
    borderBottomColor: '#F5F5F5',
    paddingBottom: 28,
  },
  exerciseName: {
    fontSize: 17,
    fontWeight: '700',
    marginBottom: 16,
    color: '#000000',
    letterSpacing: -0.2,
    textTransform: 'uppercase',
  },
  progressMetricContainer: {
    marginBottom: 18,
    backgroundColor: '#FAFAFA',
    shadowColor: '#000',
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 3,
    elevation: 2,
    padding: 16,
    borderTopRightRadius: 10,
    borderBottomRightRadius: 10,
    borderWidth: 1,
    borderColor: '#F5F5F5',
    borderLeftWidth: 4,
    borderLeftColor: '#000000',
  },
  progressMetricTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#4B5563',
    marginBottom: 10,
    letterSpacing: -0.1,
  },
  progressMetricRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 6,
  },
  progressMetricValue: {
    fontSize: 16,
    color: '#4B5563',
    fontWeight: '400',
  },
  progressMetricChange: {
    fontWeight: '700',
    fontSize: 16,
    letterSpacing: -0.1,
  },
  chartSummaryContainer: {
    alignItems: 'center',
    paddingVertical: 16,
  },
  chartTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: '#000000',
    marginBottom: 32,
    textAlign: 'center',
    letterSpacing: -0.5,
    textTransform: 'uppercase',
  },
  chartLegendContainer: {
    marginTop: 8,
    padding: 12,
    borderRadius: 8,
  },
  chartLegendText: {
    fontSize: 14,
    textAlign: 'center',
  },
  emptyProgressCard: {
    backgroundColor: '#FFFFFF',
    paddingVertical: 32,
    paddingHorizontal: 20,
    marginHorizontal: 20,
    borderRadius: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 3,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 180,
    borderWidth: 1,
    borderColor: '#F5F5F5',
  },
  emptyText: {
    textAlign: 'center',
    color: '#6B7280',
    fontSize: 15,
    lineHeight: 22,
    letterSpacing: 0.1,
    fontWeight: '400',
  },
  comparisonToggleContainer: {
    flexDirection: 'row',
    marginBottom: 16,
    marginHorizontal: 20,
    borderRadius: 8,
    overflow: 'visible',
    borderWidth: 1,
    borderColor: '#EEEEEE',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 6,
    backgroundColor: '#FFFFFF',
  },
  comparisonToggleButton: {
    flex: 1,
    paddingVertical: 12,
    alignItems: 'center',
    borderRadius: 8,
  },
  selectedComparisonToggleButton: {
    backgroundColor: '#000000',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
    borderRadius: 8,
  },
  unselectedComparisonToggleButton: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
  },
  comparisonToggleText: {
    fontWeight: '600',
    fontSize: 14,
    letterSpacing: -0.2,
  },
  selectedComparisonToggleText: {
    color: '#FFFFFF',
  },
  unselectedComparisonToggleText: {
    color: '#000000',
  },
  progressCardItem: {
    marginBottom: 16,
    padding: 16,
    borderRadius: 8,
    borderWidth: 1,
  },
  progressCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  metricIconContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  metricIcon: {
    width: 36,
    height: 36,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  progressCardMetricTitle: {
    fontSize: 16,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: -0.2,
  },
  progressCardBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
  },
  progressCardBadgeText: {
    fontSize: 12,
    fontWeight: '800',
  },
  progressCardContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  progressCardValues: {
    flex: 1,
  },
  progressCardCurrentValue: {
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 4,
  },
  progressCardInitialValue: {
    fontSize: 14,
  },
  progressCardAbsoluteChange: {
    fontSize: 24,
    fontWeight: '800',
  },
  progressCardContainer: {
    width: '100%',
    marginTop: 16,
    marginBottom: 16,
  },
});
